### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by AndyHoggANU** [aidanheerdegen/publish_cosima_data#15]
I'm now up to running this on the access-om2-01 simulation. I have two problems.

The first issue is related to running out of memory. If I try to run the whole dataset I run out of memory - even with 192Gb and only 2 cores. I'm not sure what the limit is, but I can get it to work if I subset it to output00?. 

So I could run everything piece by piece ... but I will end up with part-years in some files. It would be possible to ensure each piece ended up with a full year, but that seems pretty manual, so maybe there is a better solution?

The second problem is with ice -- it is telling me that TLON is not consistent between files, but I haven't investigated this in detail - will try to do this and if I can't figure it out will start a new thread on that one.

**Comment by aidanheerdegen** [comment]
This commit https://github.com/aidanheerdegen/publish_cosima_data/commit/7a73ee9c9bb6a7c72ec984298714e295bd29c1bc fixes the memory issues by submitting all jobs to the PBS queues.

This corresponds to version `0.2.5` which is installed in `conda/analysis3-unstable`
