### ISSUE TITLE
Some 2D cases working ...

### ISSUE THREAD

**Issue by AndyHoggANU** [aidanheerdegen/publish_cosima_data#16]
I'm now running the latest version which seems to have worked in some cases. As far as I can tell the ice and some 2D variables worked. 

However, not all the 2D variables were saved. For example, tau-y looks fine, but tau-x gives an error which ends in:
```
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (26, 2700, 3600) and data type float32
```
Strange that tau-y was OK, but tau-x isn't, as they are obviously the same size.

**Comment by aidanheerdegen** [comment]
Yeah, weird. I guess just up the memory a bit? Currently it is 10Gb, so maybe set to 15 or 20.

**Comment by AndyHoggANU** [comment]
OK, will try those ones with extra memory now.

**Comment by AndyHoggANU** [comment]
Tried with extra memory. It seemed to work for 20 of the 28 variables. No particular pattern to those that failed, so I will try them again.

**Comment by AndyHoggANU** [comment]
An update on this one. I have now tried to process all the 2D variables. For some variables it works every time. For `sw_heat` and `sfc_hflux_coupler` it never works. I can't extract an error message or a patterns for which ones go through and which don't, but you can get an idea of the hit rate from looking at the size of directories:
```
amh157@raijin2:ocean %% du -sh ./*
15G	./bmf-u
12G	./bmf-v
15G	./evap
15G	./melt
9.2G	./mld
15G	./net-sfc-heating
12G	./pme-river
12G	./river
15G	./runoff
15G	./sea-levelsq
15G	./sfc-hflux-from-runoff
12G	./sfc-hflux-pme
15G	./sfc-salt-flux-coupler
12G	./sfc-salt-flux-ice
15G	./sfc-salt-flux-restore
15G	./surface-salt
15G	./surface-temp
15G	./swflx
15G	./tau-x
15G	./tau-y
7.6G	./temp-xflux-adv-int-z
7.6G	./temp-xflux-submeso-int-z
17G	./temp-yflux-adv-int-z
7.6G	./temp-yflux-submeso-int-z
14G	./tx-trans-int-z
14G	./ty-trans-int-z
```
It is probably possible to get there, eventually, but would be better if I can figure out why some attempts are dying.

**Comment by AndyHoggANU** [comment]
I think I have rectified this issue. It was just memory, after all. I put it on express with 40Gb, just like the ice, and it seems to be behaving itself. I've only tested it on a few variables. Will run for all variables overnight and see how it goes.
