### ISSUE TITLE
File name convention has changed

### ISSUE THREAD

**Issue by AndyHoggANU** [aidanheerdegen/publish_cosima_data#20]
I decided to re-run everything from scratch. Looks like monthly files are OK, but the file name conventions for the annual 3D files has changed. They used to be in the form *195801-195812...
But now they just say *195807-195807... which is not ideal.

Any chance we can refine this?

**Comment by aidanheerdegen** [comment]
A fix for this is to use the `--datefrombounds` option to `splitvar`.

This gives an output naming result like so:

```
-rw-rw----+ 1 aph502 ua8 22513736 Oct 18 11:58 temp_access-om2_195801_195901.nc
-rw-rw----+ 1 aph502 ua8 22513736 Oct 18 11:58 temp_access-om2_195901_196001.nc
```

While it isn't ideal that the end date is the January of the next year this just reflects what is in the `time_bounds` variable:
```
ncdump -v time_bounds /g/data3/hh5/tmp/cosima/access-om2/1deg_jra55v13_iaf_spinup1_B1/output000/ocean/ocean.nc

...
data:

 time_bounds =
  0, 365,
  365, 730,
  730, 1096,
  1096, 1461,
  1461, 1826 ;
}
```

The time bounds overlap.

I *could* make a dummy time series, resample that and use the end dates of the dummy series for this. Let me know what you think.

**Comment by aidanheerdegen** [comment]
Another option is to have the option to subtract one from the end bound. Treat it as a convention that end bound is open and start bound is closed

(see https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Interval.html for discussion of open/closed bounds)

**Comment by AndyHoggANU** [comment]
I have opted for the simplest one here using `--datefrombounds`. Seems to work nicely.
