### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by AndyHoggANU** [aidanheerdegen/publish_cosima_data#3]
Aggregation onto a year seemed to do a good job, but the time information in the netcdf file wasn't retained. see `u_access-om2_219812_219812.nc`

**Comment by aidanheerdegen** [comment]
Worked for me:
```
netcdf u_access-om2_219812_219812 {
dimensions:
        time = UNLIMITED ; // (1 currently)
        yu_ocean = 300 ;
        st_ocean = 50 ;
        xu_ocean = 360 ;
```
But I can see it didn't for you:
```
$ ncdump -h /g/data1/ua8/cosima-tmp/publish/access-om2/ocean/u/u_access-om2_219812_219812.nc 
netcdf u_access-om2_219812_219812 {
dimensions:
        time = 1 ;
        xu_ocean = 360 ;
        st_ocean = 50 ;
        yu_ocean = 300 ;
```
Odd. Maybe a version difference in `splitvar`? I'll add a line to HISTORY with splitvar version and how it was invoked. Should have that anyway.

**Comment by AndyHoggANU** [comment]
OK, I think my issues may partly stem from the version of splitvar that I'm using ... I thought I would pick this up with the unstable conda implementation. But do I need to do anything more there?

**Comment by aidanheerdegen** [comment]
I have fixed some of the issues with aggregation relating to the dependent variables, such as `time_bounds`, which need a different aggregation function. The branch is here:

https://github.com/coecms/splitvar/tree/bounds

but I haven't merged it yet, or installed into the `conda` env. Still got to change the dates etc.
